server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.96.238.166:3306/es-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd

mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-handlers-package: com.tianqi.common.handler.type